name: Publish NPM package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        run: |
          deno task lint

      - name: Test
        run: |
          deno test

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Build npm package
        run: |
          deno task build-npm ${{ github.event.release.tag_name }}

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd npm && npm publish --access public
