name: Publish NPM package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        run: |
          deno task lint

      - name: Test
        run: |
          deno test
